/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

/**
 *
 * @author walde
 */
public class FormSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form FormSecretaria
     */
    public FormSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllogoSecretaria = new javax.swing.JLabel();
        lblCadSec = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        lbllogoSecretaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SECRETARIAS.png"))); // NOI18N
        lbllogoSecretaria.setDisabledIcon(null);
        getContentPane().add(lbllogoSecretaria);
        lbllogoSecretaria.setBounds(40, 10, 111, 109);

        lblCadSec.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCadSec.setText("Cadatro de Secretarias");
        getContentPane().add(lblCadSec);
        lblCadSec.setBounds(160, 40, 440, 50);

        jLabel1.setText("SECRETARIA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 140, 80, 14);

        jLabel2.setText("SIGLA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 140, 29, 14);

        jLabel3.setText("SERETARIO(A)/ RESONSÁVEL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 200, 170, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(40, 160, 410, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(460, 160, 160, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(40, 220, 580, 30);

        jButton1.setText("Adicionar");
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 273, 80, 60);

        jButton2.setText("Localizar");
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 290, 73, 23);

        jButton3.setText("Excluir");
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 290, 63, 23);

        jButton4.setText("Sair");
        getContentPane().add(jButton4);
        jButton4.setBounds(530, 290, 51, 23);

        jButton5.setText("Alterar");
        getContentPane().add(jButton5);
        jButton5.setBounds(310, 290, 65, 23);

        setSize(new java.awt.Dimension(657, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        TelaPrincipal principal = new TelaPrincipal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblCadSec;
    private javax.swing.JLabel lbllogoSecretaria;
    // End of variables declaration//GEN-END:variables
}
