
package visão;

import java.sql.*;
import ConexaoBanco.ModuloConexao;
import javax.swing.JOptionPane;

/**
 *
 * @author walde
 */
public class FormSecretaria extends javax.swing.JFrame {

Connection conexao = null;
PreparedStatement pst = null;
ResultSet rs = null;    
    /**
     * Creates new form FormSecretaria
     */
    public FormSecretaria() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    //método para adicionar secretarias
    private void adicionar(){
        String sql = "insert into tbsecretarias(nomesecretaria,sigla,secretario)values(?,?,?)";
        
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,txtsecretaria.getText());
            pst.setString(2,txtsigla.getText());
            pst.setString(3,txtsecretario.getText());
            
            
            if ((txtsecretaria.getText().isEmpty())|| (txtsigla.getText().isEmpty())||(txtsecretario.     getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            }else {
                int adicionado = pst.executeUpdate();
                
                if (adicionado > 0){
                    JOptionPane.showMessageDialog(null, "Secretaria adicionado com sucesso");
                    
                    txtsecretaria.setText(null);
                    txtsigla.setText(null);
                    txtsecretario.setText(null);
               }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllogoSecretaria = new javax.swing.JLabel();
        lblCadSec = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsecretaria = new javax.swing.JTextField();
        txtsigla = new javax.swing.JTextField();
        txtsecretario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnatualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        lbllogoSecretaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SECRETARIAS.png"))); // NOI18N
        lbllogoSecretaria.setDisabledIcon(null);
        getContentPane().add(lbllogoSecretaria);
        lbllogoSecretaria.setBounds(40, 10, 111, 109);

        lblCadSec.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCadSec.setText("Cadatro de Secretarias");
        getContentPane().add(lblCadSec);
        lblCadSec.setBounds(160, 40, 480, 50);

        jLabel1.setText("SECRETARIA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 170, 100, 17);

        jLabel2.setText("SIGLA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 170, 50, 17);

        jLabel3.setText("SECRETARIO(A)/ RESPONSÁVEL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 230, 220, 17);

        txtsecretaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtsecretaria);
        txtsecretaria.setBounds(70, 190, 410, 30);

        txtsigla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtsigla);
        txtsigla.setBounds(490, 190, 160, 30);

        txtsecretario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtsecretario);
        txtsecretario.setBounds(70, 250, 580, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados da Secretaria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 150, 620, 150);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 130, 660, 200);

        btnAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnAdiconar.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar");
        btnAdicionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdicionar.setContentAreaFilled(false);
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(190, 350, 50, 50);

        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnLocalizar.png"))); // NOI18N
        btnLocalizar.setToolTipText("Pesquisar");
        btnLocalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLocalizar.setContentAreaFilled(false);
        btnLocalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnLocalizar);
        btnLocalizar.setBounds(270, 350, 50, 50);

        btnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnExcluir.png"))); // NOI18N
        btnexcluir.setToolTipText("Excluir");
        btnexcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnexcluir.setContentAreaFilled(false);
        btnexcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnexcluir);
        btnexcluir.setBounds(360, 350, 50, 50);

        btnatualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnAlterar.png"))); // NOI18N
        btnatualizar.setToolTipText("Atutalizar");
        btnatualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnatualizar.setContentAreaFilled(false);
        btnatualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnatualizar);
        btnatualizar.setBounds(440, 350, 50, 50);

        setSize(new java.awt.Dimension(729, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        TelaPrincipal principal = new TelaPrincipal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // chamando o metodo adicionar
        adicionar();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCadSec;
    private javax.swing.JLabel lbllogoSecretaria;
    private javax.swing.JTextField txtsecretaria;
    private javax.swing.JTextField txtsecretario;
    private javax.swing.JTextField txtsigla;
    // End of variables declaration//GEN-END:variables
}
