/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import javax.swing.JInternalFrame;

/**
 *
 * @author walde
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInernal = new javax.swing.JPanel();
        jLabelPainelCadastro = new javax.swing.JLabel();
        jButtonCadNFe = new javax.swing.JButton();
        jButtonCadEmpresas = new javax.swing.JButton();
        jButtonCadSecretarias = new javax.swing.JButton();
        jButtonRelDespacho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelPanelFundo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelApresentação = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        menuCadEmpresas = new javax.swing.JMenuItem();
        menuCadSecretarias = new javax.swing.JMenuItem();
        menuCadNF = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuDespachos = new javax.swing.JMenu();
        jMenuItemFinanceiro = new javax.swing.JMenuItem();
        jMenuItemFundos = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBenvindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelInernal.setBackground(new java.awt.Color(255, 239, 238));
        jPanelInernal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInernal.setLayout(null);

        jLabelPainelCadastro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPainelCadastro.setText("CADASTRO");
        jPanelInernal.add(jLabelPainelCadastro);
        jLabelPainelCadastro.setBounds(20, 20, 110, 30);

        jButtonCadNFe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IcoNF.png"))); // NOI18N
        jButtonCadNFe.setToolTipText("Lançar Notas Fiscais");
        jPanelInernal.add(jButtonCadNFe);
        jButtonCadNFe.setBounds(260, 60, 110, 110);

        jButtonCadEmpresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IcoEmp.png"))); // NOI18N
        jButtonCadEmpresas.setToolTipText("Cadastrar Empresas");
        jButtonCadEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadEmpresasActionPerformed(evt);
            }
        });
        jButtonCadEmpresas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCadEmpresasKeyPressed(evt);
            }
        });
        jPanelInernal.add(jButtonCadEmpresas);
        jButtonCadEmpresas.setBounds(20, 60, 110, 110);

        jButtonCadSecretarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SECRETARIAS.png"))); // NOI18N
        jButtonCadSecretarias.setToolTipText("Cadastrar Secretarias");
        jButtonCadSecretarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadSecretariasActionPerformed(evt);
            }
        });
        jButtonCadSecretarias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCadSecretariasKeyPressed(evt);
            }
        });
        jPanelInernal.add(jButtonCadSecretarias);
        jButtonCadSecretarias.setBounds(140, 60, 110, 110);

        jButtonRelDespacho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DESPACHOS.png"))); // NOI18N
        jButtonRelDespacho.setToolTipText("Despacho de Notas / Empenhos");
        jPanelInernal.add(jButtonRelDespacho);
        jButtonRelDespacho.setBounds(20, 210, 110, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RELATÓRIO");
        jPanelInernal.add(jLabel1);
        jLabel1.setBounds(20, 180, 130, 22);

        jLabelPanelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telaengrenage.png"))); // NOI18N
        jPanelInernal.add(jLabelPanelFundo);
        jLabelPanelFundo.setBounds(10, 10, 890, 310);

        getContentPane().add(jPanelInernal);
        jPanelInernal.setBounds(30, 150, 900, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 0, 210, 130);

        jLabelApresentação.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelApresentação.setText("Sistema de Gerenciamento ");
        getContentPane().add(jLabelApresentação);
        jLabelApresentação.setBounds(320, 60, 590, 70);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(-6, 0, 970, 540);

        jMenuCadastro.setText("Cadastro");

        menuCadEmpresas.setText("Empresas");
        menuCadEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadEmpresasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(menuCadEmpresas);

        menuCadSecretarias.setText("Secretarias");
        menuCadSecretarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadSecretariasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(menuCadSecretarias);

        menuCadNF.setText("Notas Fiscal");
        jMenuCadastro.add(menuCadNF);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorio.setText("Relatório");

        jMenuDespachos.setText("Despachos");

        jMenuItemFinanceiro.setText("Financeiro");
        jMenuDespachos.add(jMenuItemFinanceiro);

        jMenuItemFundos.setText("Fundos");
        jMenuDespachos.add(jMenuItemFundos);

        jMenuRelatorio.add(jMenuDespachos);

        jMenuBar1.add(jMenuRelatorio);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBenvindo.setText("Tela Bem vindos");
        jMenuItemTelaBenvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBenvindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBenvindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("Principal");

        setSize(new java.awt.Dimension(977, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void chamaEmpresa(){
        FormEmpresa empresa = new FormEmpresa();
        empresa.setVisible(true);
        this.dispose();
        
    }
    private void chamaSecretaria(){
        FormSecretaria secretaria = new FormSecretaria();
        secretaria.setVisible(true);
        this.dispose();
    }
    private void menuCadEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadEmpresasActionPerformed
        // TODO add your handling code here:
        chamaEmpresa();
    }//GEN-LAST:event_menuCadEmpresasActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemTelaBenvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBenvindoActionPerformed
       // TelaPrincipal tela = new TelaPrincipal();
        //tela.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jMenuItemTelaBenvindoActionPerformed

    private void jButtonCadEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadEmpresasActionPerformed
          // TODO add your handling code here:
          chamaEmpresa();
    }//GEN-LAST:event_jButtonCadEmpresasActionPerformed

    private void menuCadSecretariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadSecretariasActionPerformed
        // TODO add your handling code here:
          chamaSecretaria();
        
    }//GEN-LAST:event_menuCadSecretariasActionPerformed

    private void jButtonCadSecretariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadSecretariasActionPerformed
        // TODO add your handling code here:
          chamaSecretaria();
        
    }//GEN-LAST:event_jButtonCadSecretariasActionPerformed

    private void jButtonCadEmpresasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCadEmpresasKeyPressed
        // TODO add your handling code here:
        chamaEmpresa();
    }//GEN-LAST:event_jButtonCadEmpresasKeyPressed

    private void jButtonCadSecretariasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCadSecretariasKeyPressed
        // TODO add your handling code here:
        chamaSecretaria();
    }//GEN-LAST:event_jButtonCadSecretariasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadEmpresas;
    private javax.swing.JButton jButtonCadNFe;
    private javax.swing.JButton jButtonCadSecretarias;
    private javax.swing.JButton jButtonRelDespacho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApresentação;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelCadastro;
    private javax.swing.JLabel jLabelPanelFundo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuDespachos;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemFinanceiro;
    private javax.swing.JMenuItem jMenuItemFundos;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBenvindo;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInernal;
    private javax.swing.JMenuItem menuCadEmpresas;
    private javax.swing.JMenuItem menuCadNF;
    private javax.swing.JMenuItem menuCadSecretarias;
    // End of variables declaration//GEN-END:variables
}
